from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from publisher import (
    _cloudflare_credentials,
    _deploy_cloudflare_pages,
    _deploy_with_vercel_cli,
    _ensure_cloudflare_project,
    _ensure_private_github_repo,
    _remove_vercel_oidc_env,
    _replace_remote_main,
    _resolve_git_author,
    _set_cloudflare_site_url,
    _set_vercel_site_url,
    _validate_project,
    _vercel_project_payload,
    _verify_online_deployment,
)


class PublisherValidationTests(unittest.TestCase):
    def test_cloudflare_credentials_accept_preferred_and_legacy_names(self) -> None:
        self.assertEqual(
            _cloudflare_credentials({
                "CLOUDFLARE_ACCOUNT_ID": "account",
                "CLOUDFLARE_API_TOKEN": "token",
            }),
            ("account", "token"),
        )
        self.assertEqual(
            _cloudflare_credentials({
                "cf_accountid": "legacy-account",
                "cf_pages_api_key": "legacy-token",
            }),
            ("legacy-account", "legacy-token"),
        )
        with self.assertRaisesRegex(RuntimeError, "requires CLOUDFLARE_ACCOUNT_ID"):
            _cloudflare_credentials({})

    @patch("publisher._cloudflare_request")
    def test_cloudflare_project_creation_is_direct_upload(self, request) -> None:
        request.side_effect = [
            RuntimeError("HTTP 404 from project"),
            {"id": "project-id", "name": "game", "source": None},
        ]
        project = _ensure_cloudflare_project("account", "token", "game")
        self.assertEqual(project["id"], "project-id")
        self.assertEqual(request.call_args_list[1].args[0], "POST")
        self.assertEqual(
            request.call_args_list[1].args[4],
            {"name": "game", "production_branch": "main"},
        )

    @patch("publisher._cloudflare_request")
    def test_cloudflare_site_url_patch_is_scoped_to_production(self, request) -> None:
        _set_cloudflare_site_url(
            "account", "token", "game", "https://game.example"
        )
        payload = request.call_args.args[4]
        self.assertEqual(
            payload["deployment_configs"]["production"]["env_vars"]["NEXT_PUBLIC_SITE_URL"],
            {"type": "plain_text", "value": "https://game.example"},
        )
        self.assertNotIn("token", json.dumps(payload).casefold())

    @patch("publisher._find_cloudflare_deployment")
    @patch("publisher._run_logged")
    @patch("publisher._set_cloudflare_site_url")
    @patch("publisher._ensure_cloudflare_project")
    @patch("publisher.shutil.which")
    def test_cloudflare_deploy_keeps_token_out_of_argv(
        self, which, ensure_project, set_site_url, run_logged, find_deployment
    ) -> None:
        which.side_effect = lambda name: name
        ensure_project.return_value = {
            "id": "project-id",
            "name": "game",
            "subdomain": "game.pages.dev",
            "source": None,
        }
        run_logged.side_effect = ["build ok", "https://deploy.game.pages.dev"]
        find_deployment.return_value = {
            "id": "deployment-id",
            "url": "https://deploy.game.pages.dev",
            "latest_stage": {"status": "success"},
        }
        result = _deploy_cloudflare_pages(
            Path("C:/game"),
            "game",
            "game.example/path",
            "abc123",
            {"cf_accountid": "account", "cf_pages_api_key": "hidden-token"},
        )
        deploy_call = run_logged.call_args_list[1]
        command = deploy_call.args[0]
        command_env = deploy_call.args[2]
        self.assertNotIn("hidden-token", command)
        self.assertEqual(command_env["CLOUDFLARE_API_TOKEN"], "hidden-token")
        self.assertEqual(command_env["NEXT_PUBLIC_SITE_URL"], "https://game.example")
        self.assertEqual(result["status"], "deployed")
        self.assertEqual(result["deploymentMode"], "direct-upload")
        set_site_url.assert_called_once_with(
            "account", "hidden-token", "game", "https://game.example"
        )

    def test_only_vercel_oidc_env_is_removed_automatically(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project = Path(temporary)
            env_file = project / ".env.local"
            env_file.write_text("# Generated by Vercel\nVERCEL_OIDC_TOKEN=secret\n", encoding="utf-8")
            self.assertTrue(_remove_vercel_oidc_env(project))
            self.assertFalse(env_file.exists())

            env_file.write_text("VERCEL_OIDC_TOKEN=secret\nAD_NATIVE_BANNER=keep\n", encoding="utf-8")
            self.assertFalse(_remove_vercel_oidc_env(project))
            self.assertTrue(env_file.exists())

    def _project(self, root: Path) -> Path:
        (root / ".gamewiki").mkdir()
        (root / "intake").mkdir()
        (root / ".gamewiki" / "manifest.json").write_text(json.dumps({"status": "complete"}), encoding="utf-8")
        (root / "package.json").write_text("{}", encoding="utf-8")
        for name in ("site-identity.json", "site-content.json", "site-plan.json"):
            (root / "intake" / name).write_text("{}", encoding="utf-8")
        (root / "intake" / "factory-release.json").write_text(
            json.dumps({"release": "v1_0722"}), encoding="utf-8"
        )
        return root

    def test_complete_project_is_publishable(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            manifest = _validate_project(self._project(Path(temporary)))
        self.assertEqual(manifest["status"], "complete")

    def test_secret_file_blocks_publish(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project = self._project(Path(temporary))
            (project / ".env.production").write_text("TOKEN=secret", encoding="utf-8")
            with self.assertRaisesRegex(RuntimeError, "Secret-like"):
                _validate_project(project)

    def test_unstamped_legacy_project_cannot_publish(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project = self._project(Path(temporary))
            (project / "intake" / "factory-release.json").unlink()
            with self.assertRaisesRegex(RuntimeError, "factory-release"):
                _validate_project(project)

    @patch("publisher._run")
    def test_existing_public_repository_is_made_private_and_rechecked(self, run) -> None:
        run.side_effect = ["PUBLIC", "", "PRIVATE"]

        _ensure_private_github_repo("owner/game", Path("C:/game"), {"GH_TOKEN": "hidden"})

        commands = [call.args[0] for call in run.call_args_list]
        self.assertIn("--visibility", commands[1])
        self.assertIn("private", commands[1])
        self.assertEqual(commands[0], commands[2])

    @patch("publisher._run", return_value="PUBLIC")
    def test_private_visibility_is_a_required_postcondition(self, _run) -> None:
        with self.assertRaisesRegex(RuntimeError, "must be PRIVATE"):
            _ensure_private_github_repo("owner/game", Path("C:/game"), {})

    def test_vercel_project_creation_never_sets_environment_variables(self) -> None:
        payload = _vercel_project_payload("game", "owner/game")
        self.assertNotIn("environmentVariables", payload)
        self.assertEqual(payload["gitRepository"]["repo"], "owner/game")

    @patch("publisher.subprocess.run")
    @patch("publisher._run")
    def test_replace_remote_main_backs_up_then_uses_force_with_lease(self, run, subprocess_run) -> None:
        run.side_effect = lambda command, *_args, **_kwargs: "abc123" if command[:3] == ["git", "rev-parse", "refs/remotes/origin/main"] else ""
        tag = _replace_remote_main(
            Path("C:/game"),
            "owner/game",
            {},
            ("declanliang", "130889021+declanliang@users.noreply.github.com"),
        )
        commands = [call.args[0] for call in run.call_args_list]
        self.assertTrue(tag.startswith("pre-rebuild-"))
        self.assertTrue(any(command[:3] == ["git", "push", "origin"] and "refs/tags/" in command[3] for command in commands))
        self.assertTrue(any(command[:2] == ["git", "push"] and "--force-with-lease=main:abc123" in command for command in commands))
        commit = next(command for command in commands if "commit" in command)
        self.assertIn("user.name=declanliang", commit)
        self.assertIn("user.email=130889021+declanliang@users.noreply.github.com", commit)

    @patch("publisher._run", return_value="declanliang\t130889021")
    def test_git_author_uses_authenticated_github_noreply_identity(self, run) -> None:
        author = _resolve_git_author(Path("C:/game"), {"GH_TOKEN": "hidden"})
        self.assertEqual(author, ("declanliang", "130889021+declanliang@users.noreply.github.com"))
        self.assertNotIn("hidden", run.call_args.args[0])

    @patch("publisher.shutil.which", return_value="vercel")
    @patch("publisher._run")
    def test_explicit_site_url_sets_production(self, run, _which) -> None:
        origin = _set_vercel_site_url(Path("C:/game"), "game", "game.example/path")
        self.assertEqual(origin, "https://game.example")
        commands = [call.args[0] for call in run.call_args_list]
        self.assertEqual(commands[0][:4], ["vercel", "link", "--yes", "--project"])
        self.assertEqual(commands[1][4], "production")

    @patch("publisher.shutil.which", return_value="vercel")
    @patch("publisher._run", side_effect=["", "https://game.vercel.app"])
    def test_deploy_links_existing_vercel_project_before_production(self, run, _which) -> None:
        url = _deploy_with_vercel_cli(Path("C:/game"), "existing-project", {"VERCEL_TOKEN": "hidden"})
        commands = [call.args[0] for call in run.call_args_list]
        self.assertEqual(commands[0][:5], ["vercel", "link", "--yes", "--project", "existing-project"])
        self.assertIn("--prod", commands[1])
        self.assertNotIn("hidden", commands[0])
        self.assertNotIn("hidden", commands[1])
        self.assertNotIn("--token", commands[0])
        self.assertNotIn("--token", commands[1])
        self.assertEqual(url, "https://game.vercel.app")

    @patch("publisher.shutil.which", return_value="vercel")
    @patch("publisher._run", side_effect=["", 'Production: https://game.vercel.app\nhttps://api.vercel.com/v13/deployments/dpl_123"'])
    def test_deploy_receipt_ignores_internal_vercel_api_url(self, run, _which) -> None:
        url = _deploy_with_vercel_cli(Path("C:/game"), "game", {})
        self.assertEqual(url, "https://game.vercel.app")

    @patch("publisher.shutil.which", return_value="vercel")
    @patch("publisher._run", side_effect=["", "Production: https://game-abc.vercel.app\nInspect: https://vercel.com/team/game/deployment"])
    def test_deploy_receipt_prefers_deployment_over_dashboard_url(self, run, _which) -> None:
        url = _deploy_with_vercel_cli(Path("C:/game"), "game", {})
        self.assertEqual(url, "https://game-abc.vercel.app")

    @patch("publisher.shutil.which", return_value="npm")
    @patch("publisher.subprocess.run")
    def test_online_verification_is_a_logged_publish_postcondition(self, run, _which) -> None:
        run.return_value.returncode = 0
        run.return_value.stdout = "0 error(s).\n"
        run.return_value.stderr = ""
        with tempfile.TemporaryDirectory() as temporary:
            project = Path(temporary)
            result = _verify_online_deployment(project, "https://game.example/", {"TOKEN": "hidden"})
            log = (project / ".gamewiki" / "deploy-verification.log").read_text(encoding="utf-8")
        self.assertEqual(result["status"], "complete")
        self.assertEqual(result["origin"], "https://game.example")
        self.assertIn("0 error(s).", log)
        command = run.call_args.args[0]
        self.assertEqual(command, ["npm", "run", "verify:deploy"])
        self.assertEqual(run.call_args.kwargs["env"]["NEXT_PUBLIC_SITE_URL"], "https://game.example")
        self.assertNotIn("hidden", command)

    @patch("publisher.shutil.which", return_value="npm")
    @patch("publisher.subprocess.run")
    def test_online_verification_failure_blocks_publish(self, run, _which) -> None:
        run.return_value.returncode = 1
        run.return_value.stdout = "online sitemap target returned 404"
        run.return_value.stderr = ""
        with tempfile.TemporaryDirectory() as temporary:
            project = Path(temporary)
            with self.assertRaisesRegex(RuntimeError, "online deployment verification failed"):
                _verify_online_deployment(project, "https://game.example", {})
            self.assertTrue((project / ".gamewiki" / "deploy-verification.log").is_file())


if __name__ == "__main__":
    unittest.main()
