#!/usr/bin/env node
// Selects only from reviewed palettes. Arbitrary model-generated colors are not
// accepted because they cannot guarantee contrast in both light and dark modes.

import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const inputPath = path.join(root, "intake", "site-theme.json");
const outputPath = path.join(root, "src", "config", "theme.ts");
const manifestColors = {
  arcade: "#6842c2",
  forest: "#247a48",
  ocean: "#176f8d",
  ember: "#a83d2a",
  mystic: "#7b3fa0",
  industrial: "#52616f",
};
if (!fs.existsSync(inputPath)) throw new Error("缺少 intake/site-theme.json");
const value = JSON.parse(fs.readFileSync(inputPath, "utf-8"));
if (value.schemaVersion !== 1 || !Object.hasOwn(manifestColors, value.preset)) {
  throw new Error(`site-theme.preset 必须是：${Object.keys(manifestColors).join(", ")}`);
}
fs.writeFileSync(
  outputPath,
  `// Generated by scripts/sync-theme.mjs from intake/site-theme.json.\n`
    + `export const SITE_THEME = ${JSON.stringify(value.preset)};\n`
    + `export const THEME_MANIFEST_COLOR = ${JSON.stringify(manifestColors[value.preset])};\n`,
  "utf-8",
);
console.log(`✓ 站点主题：${value.preset}`);
