// Generated by scripts/sync-publication.mjs from intake/publication-plan.json.
// Do not edit this file by hand.
export const GENERATED_LOCALES = ["en"] as const;
export type GeneratedLocale = (typeof GENERATED_LOCALES)[number];

export const PUBLISHED_LOCALES = ["en"] as const satisfies readonly GeneratedLocale[];
export type PublishedLocale = (typeof PUBLISHED_LOCALES)[number];
